pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk 'JDK17'
    }

    environment {
        REPORT_PATH = 'reports/ExtentReport.html'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'feature_rachit13042026',
                    url: 'https://github.com/RS125772/selenium-java-capstone.git'
            }
        }

        stage('Build & Test') {
            steps {
                script {
                    try {
                        bat 'mvn clean test -Dsurefire.suiteXmlFiles=src/test/resources/testng.xml -Dbrowser=chrome-headless'
                    } catch (Exception e) {
                        echo 'Tests failed, continuing pipeline...'
                        currentBuild.result = 'UNSTABLE'
                    }
                }
            }
        }

        stage('Publish Test Results') {
            steps {
                junit '**/surefire-reports/*.xml'
            }
        }

        stage('Publish Extent Report') {
            steps {
                publishHTML([
                    allowMissing: true,
                    alwaysLinkToLastBuild: true,
                    keepAll: true,
                    reportDir: 'reports',
                    reportFiles: 'ExtentReport.html',
                    reportName: 'Extent Test Report'
                ])
            }
        }

        stage('Archive Reports') {
            steps {
                archiveArtifacts artifacts: 'reports/**', fingerprint: true
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'reports/**', allowEmptyArchive: true

            emailext(
    subject: "Automation Report - ${currentBuild.currentResult}",
    body: """
    <html>
    <head>
        <style>
            body {
                font-family: Arial, sans-serif;
                background-color: #f4f6f8;
                margin: 0;
                padding: 0;
            }
            .container {
                max-width: 700px;
                margin: 20px auto;
                background: #ffffff;
                border-radius: 8px;
                padding: 20px;
                box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            }
            .header {
                text-align: center;
                padding-bottom: 10px;
                border-bottom: 2px solid #eee;
            }
            .header h2 {
                margin: 0;
                color: #2c3e50;
            }
            .status {
                font-size: 18px;
                font-weight: bold;
                color: ${currentBuild.currentResult == 'SUCCESS' ? '"#27ae60"' : '"#e74c3c"'};
            }
            .details {
                margin-top: 20px;
            }
            .details table {
                width: 100%;
                border-collapse: collapse;
            }
            .details td {
                padding: 8px;
                border-bottom: 1px solid #eee;
            }
            .btn {
                display: inline-block;
                margin-top: 20px;
                padding: 12px 20px;
                background-color: #3498db;
                color: #ffffff !important;
                text-decoration: none;
                border-radius: 5px;
                font-weight: bold;
            }
            .footer {
                margin-top: 30px;
                font-size: 12px;
                color: #888;
                text-align: center;
            }
        </style>
    </head>

    <body>
        <div class="container">

            <div class="header">
                <h2>Automation Execution Report</h2>
                <p class="status">${currentBuild.currentResult}</p>
            </div>

            <div class="details">
                <table>
                    <tr>
                        <td><b>Job Name</b></td>
                        <td>${env.JOB_NAME}</td>
                    </tr>
                    <tr>
                        <td><b>Build Number</b></td>
                        <td>#${env.BUILD_NUMBER}</td>
                    </tr>
                    <tr>
                        <td><b>Build URL</b></td>
                        <td><a href="${env.BUILD_URL}">${env.BUILD_URL}</a></td>
                    </tr>
                </table>
            </div>

            <div style="text-align:center;">
                <a class="btn" href="${env.BUILD_URL}artifact/${REPORT_PATH}">
                    View Detailed Extent Report
                </a>
            </div>

            <div class="footer">
                This is an automated email generated by Jenkins.
            </div>

        </div>
    </body>
    </html>
    """,
    to: 'rahul.k4@zensar.com,rachit.saurabh@zensar.com',
    mimeType: 'text/html',
    attachmentsPattern: "${REPORT_PATH}"
)
        }

        success {
            echo 'Pipeline executed successfully!'
        }

        unstable {
            echo 'Build is unstable (test failures present)'
        }

        failure {
            echo 'Pipeline failed!'
        }
    }
}
