browser=chrome
url=https://demowebshop.tricentis.com/login
timeout=10

#Valid credentials for login test
validUsername=admin0205@gmail.com
validPassword=admin123

#Invalid credentials for login test
invalidUsername=test@test.com
invalidPassword=test123