# Browser to run tests on (chrome / edge / firefox)
browser=chrome
# Run tests in headless mode (true = no UI, false = normal browser)
headless=false
# Application URL to launch before tests
url=https://demowebshop.tricentis.com/
# Global explicit wait timeout (in seconds)
timeout=15